[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/offline"
  to = "/offline.html"
  status = 200

[[headers]]
  for = "/service-worker.js"
  [headers]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/offline.html"
  [headers]
    Cache-Control = "public, max-age=0, must-revalidate"
